import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header/Header';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get('theme')?.value
    ? (cookies().get('theme')!.value as 'dark' | 'light')
    : 'system';

  return (
    <html
      lang="en"
      className={`${theme}`}
      // prefered-theme={theme}
    >
      <body className={''}>
        <Header selectedTheme={theme} />
        {children}
      </body>
    </html>
  );
}
