import type { Metadata } from 'next';
import './globals.css';
import Header from './components/Header/Header';
import { cookies } from 'next/headers';
import { Montserrat, Dosis } from 'next/font/google';
import HeaderObserver from './components/Header/HeaderObserver';

const dosis = Dosis({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-dosis',
});
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = cookies().get('theme')?.value
    ? (cookies().get('theme')!.value as 'dark' | 'light')
    : 'system';

  return (
    <html lang="en" className={`${dosis.variable} ${montserrat.className}  ${theme}`}>
      <body className="pt-3">
        <HeaderObserver />
        <Header selectedTheme={theme} />
        {children}
      </body>
    </html>
  );
}
